# Generated by Django 4.2 on 2023-07-04 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='Followup_duration',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
