# Generated by Django 4.2.2 on 2023-07-04 08:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_vendor_followup_duration'),
    ]

    operations = [
        migrations.CreateModel(
            name='Followup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choices', models.CharField(choices=[('reject', 'reject'), ('shortlist', 'shortlist'), ('screening', 'screening'), ('selected', 'selected')], default='selected', max_length=20)),
                ('job_description', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.jobdescription')),
            ],
        ),
        migrations.AlterField(
            model_name='vendor',
            name='followup',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='next_followup',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Selected',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=200)),
                ('DOJ', models.DateField()),
                ('project_duration', models.CharField(max_length=20)),
                ('project_end_date', models.DateField()),
                ('working_person', models.CharField(max_length=20)),
                ('extend_status', models.CharField(choices=[('yes', 'yes'), ('no', 'no')], max_length=20)),
                ('extend_period', models.CharField(max_length=20)),
                ('follow_up', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.followup')),
            ],
        ),
    ]
