# Generated by Django 4.2.2 on 2023-07-04 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0005_alter_jobdescription_jd'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobdescription',
            name='status',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
