# Generated by Django 4.2.2 on 2023-07-10 06:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0007_alter_jobdescription_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='followup',
            name='choices',
        ),
        migrations.RemoveField(
            model_name='jobdescription',
            name='status',
        ),
        migrations.AddField(
            model_name='followup',
            name='status',
            field=models.CharField(default=django.utils.timezone.now, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='vendor',
            name='nda_reason',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
