# Generated by Django 4.1.5 on 2023-07-10 09:54

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0007_alter_jobdescription_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='followup',
            name='choices',
        ),
        migrations.RemoveField(
            model_name='followup',
            name='job_description',
        ),
        migrations.AddField(
            model_name='followup',
            name='status',
            field=models.CharField(default=django.utils.timezone.now, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='jobdescription',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='customer.followup'),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='nda_reason',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
